name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'feature'
  - title: '🧠 Core / Engine'
    labels:
      - 'engine'
  - title: 'Configuration'
    labels:
      - 'config'
  - title: 'Performance'
    labels:
      - 'perf'
  - title: 'Documentation'
    labels:
      - 'docs'
  - title: 'Tests'
    labels:
      - 'test'
  - title: 'Chores'
    labels:
      - 'chore'

change-template: '- $TITLE (@$AUTHOR)'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'fix'
      - 'perf'
      - 'docs'

template: |
  ## Changes
  $CHANGES
