# Retention Rules
retain_public: false
retain_assign_only_properties: true
retain_codable_properties: true
retain_unused_protocol_func_params: true

# No Objective-C interop
retain_objc_annotated: false
retain_objc_accessible: false

# Exclude test targets
exclude_tests: true

# Exclude build artifacts and tooling
index_exclude:
  - "**/.build/**"
  - "**/SourcePackages/**"
  - "**/checkouts/**"
  - "**/.github/**"
  - "**/Docs/**"

# Exclude test files from reports
report_exclude:
  - "**/Tests/**"
  - "**/*Tests.swift"

# Output
format: json

# Analysis
disable_redundant_public_analysis: false
