# Project paths
included:
  - Sources
  - Tests

# Analyzer exclusions
excluded:
  - .build
  - SourcePackages
  - DerivedData

# Analyzer rules
analyzer_rules:
  - unused_declaration
  - unused_import

# Disabled rules
disabled_rules:
  - sorted_imports
  - file_types_order
  - modifier_order
  - attributes
  - extension_access_modifier
  - explicit_acl
  - explicit_top_level_acl

# Enabled opt-in rules
opt_in_rules:
  - type_contents_order
  - force_cast
  - force_try
  - force_unwrapping
  - unavailable_function
  - no_dispatch_queue
  - no_combine
  - prefer_actor_over_class

# Type contents order
type_contents_order:
  order:
    - type_alias
    - associated_type
    - initializer
    - type_property
    - instance_property
    - subtype
    - type_method
    - other_method
    - subscript
    - deinitializer

# Naming rules
identifier_name:
  excluded:
    - id
    - lhs
    - rhs
    - ctx
    - node
    - decl

# Line length
line_length:
  warning: 120
  error: 150
