# Project paths
included:
  - Sources
  - Tests

# Analyzer exclusions
excluded:
  - SourcePackages
  - DerivedData
  - .build

# Analyzer rules
analyzer_rules:
  - unused_declaration
  - unused_import

# Disabled rules
disabled_rules:
  - sorted_imports
  - file_types_order
  - modifier_order
  - attributes
  - extension_access_modifier
  - explicit_acl
  - explicit_top_level_acl
  - trailing_comma

# Enabled opt-in rules
opt_in_rules:
  - force_cast
  - force_try
  - force_unwrapping
  - unavailable_function

# Naming rules
identifier_name:
  excluded:
    - id
    - lhs
    - rhs
    - ctx
    - node
    - decl

# Line length
line_length:
  warning: 120
  error: 150

# Set different limits for Tests
configs:
  - path: Tests/SwiftStructureTests/.swiftlint.yml
