name: Feature request
description: Propose a structural feature
title: "[Feature] "
labels: enhancement
body:
  - type: textarea
    attributes:
      label: Proposal
      description: Describe the structural change and motivation
